#!/usr/bin/env php
<?php

define('INIT_TIME', microtime(true));

require __DIR__.'/vendor/autoload.php';

use Amber\Framework\Container\Facades\CommandsCollection;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\ConsoleEvents;
use Amber\Framework\Container\Application as App;


/**
 * Loads the application.
 */
App::bootCli();
